name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: TheAlexLichter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: colinscz
          template: classic
          base: header, activity, repositories
          config_timezone: Europe/Berlin
          plugin_languages: yes
          plugin_languages_skipped: TheAlexLichter/fp-in-php, TheAlexLichter/php-is-dead-long-live-php, TheAlexLichter/map-reduce-filter-no-loops-needed
          optimize: css, xml
